name: hemo
description: "A cross-platform (iOS/Android) blood donation app built with Flutter. Hemo aims to connect donors, recipients, and blood banks to streamline the donation process."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  cloud_firestore: ^6.1.0
  equatable: ^2.0.7
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_it: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.0
  intl_phone_number_input: ^0.7.5
  logging: ^1.3.0
  phosphor_flutter: ^2.1.0
  pinput: ^6.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding-1.png
    - assets/images/onboarding-2.png
    - assets/images/onboarding-3.png

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: fonts/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  fullscreen: true